### ISSUE TITLE
Providing invalid 6-digit code makes thread panic instead of throwing a recoverable error

### ISSUE THREAD

**Issue by auspiciousArtifice** [EmperorParzival/hentai#5]
Using version 0.2.2, providing an invalid/non-existent code for Hentai::new() results in the thread panicking instead of simply throwing one of the HentaiErrors. 

This is the message that follows the panic in every instance: ``thread 'main' panicked at 'Failed to deserialize json: Error("missing field `id`", line: 1, column: 27)', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/hentai-0.2.2/src/parse.rs:75:55``

Since parse.rs is no longer present in the repo and using the latest code in the master branch seems to fix this issue, this leads me to believe the crate just hasn't been updated with more recent commits.

**Comment by EmperorParzival** [comment]
I've updated the crate along with @Bobo1239's image URL fix. Hopefully this issue is fixed.
